## Exercícios

In [1]:
import numpy as np

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [2]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
filt = (vetor % 2 != 0)
vetor_impar = vetor[filt]
print(vetor_impar)

[1 3 5 7 9]


2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [3]:
vetor[filt] = 0
print(vetor)

[0 2 0 4 0 6 0 8 0]


3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [4]:
filedata = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',')

In [5]:
filtrado = filedata[0:10,0:4]
print(filtrado)
np.shape(filtrado) #Verificando se vieram 10 linhas e 4 colunas

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


(10, 4)

In [6]:
filtrado[:,0] #Coluna da Sepal Lenght

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [7]:
media_sepallenght = np.mean(filtrado[:,0])
print(f'A média das sépalas é {media_sepallenght}')
mediana_sepallenght = np.median(filtrado[:,0])
print(f'A mediana das sépalas é {mediana_sepallenght}')
desvioPad_sepallenght = np.std(filtrado[:,0])
print(f'O desvio padrão das sépalas é {desvioPad_sepallenght}')

A média das sépalas é 4.859999999999999
A mediana das sépalas é 4.9
O desvio padrão das sépalas é 0.2764054992217051


5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [23]:
filt1 = filtrado[:,0] < 5
filt2 = filtrado[:,2] > 1.5

In [24]:
filtrado[filt1 & filt2]

array([], shape=(0, 4), dtype=float64)

6 - Esse dataset possui nans?

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3